/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#f0f7ff',
          100: '#e0f0fe',
          200: '#bae0fd',
          300: '#90cafc',
          400: '#5aacf9',
          500: '#4361ee',
          600: '#3a56d4',
          700: '#2f4bba',
          800: '#2541a1',
          900: '#1a3687',
          950: '#102a6f',
        },
        gray: {
          50: '#f9f7f4',
          100: '#f3f0e9',
          200: '#e9e4d5',
          300: '#d9d0b8',
          400: '#bfb396',
          500: '#a69b7b',
          600: '#8c8264',
          700: '#726a52',
          800: '#5e5745',
          900: '#4d483c',
          950: '#292722',
        },
        accent: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
          950: '#082f49',
        },
        neutral: {
          50: '#faf8f2',
          100: '#f5f1e6',
          200: '#ebe3d0',
          300: '#dfd0b4',
          400: '#c9b795',
          500: '#b39e7a',
          600: '#a08866',
          700: '#836f54',
          800: '#6c5c47',
          900: '#594c3d',
          950: '#302920',
        },
        background: {
          light: '#fdf8ed',
          card: '#fff9ee',
          section: '#f9f0d9',
          highlight: '#f5e7c3',
          muted: '#faf8f2',
          cream: '#fcf9f2',
          warm: '#fef6e6',
          soft: '#f8f5eb',
          pale: '#f5f2e9',
          subtle: '#f2efdf',
        }
      },
      backgroundImage: {
        'gradient-smooth': 'linear-gradient(to bottom, var(--tw-gradient-stops))',
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'gradient-section': 'linear-gradient(to bottom, #fdf8ed, #f9f0d9, #f5e7c3)',
        'gradient-hero': 'linear-gradient(to bottom, #f8f5eb, #fcf9f2)',
        'gradient-about': 'linear-gradient(to bottom, #fcf9f2, #fef6e6)',
        'gradient-projects': 'linear-gradient(to bottom, #fef6e6, #f8f5eb)',
        'gradient-contact': 'linear-gradient(to bottom, #f8f5eb, #fcf9f2)',
        'gradient-card': 'linear-gradient(to bottom right, #fff, #faf8f2)',
      },
      animation: {
        'fadeIn': 'fadeIn 0.5s ease-out forwards',
        'slideInFromLeft': 'slideInFromLeft 0.7s ease-out forwards',
        'slideInFromRight': 'slideInFromRight 0.7s ease-out forwards',
        'zoomIn': 'zoomIn 0.5s ease-out forwards',
        'float': 'float 3s ease-in-out infinite',
        'glow': 'glow 3s ease-in-out infinite',
        'pulse': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce': 'bounce 1s infinite',
        'spin': 'spin 1s linear infinite',
        'ping': 'ping 1s cubic-bezier(0, 0, 0.2, 1) infinite',
        'marquee': 'marquee 40s linear infinite',
        'marquee2': 'marquee2 40s linear infinite',
        'marquee-pause': 'marquee-pause 40s linear infinite paused',
        'marquee2-pause': 'marquee2-pause 40s linear infinite paused',
        'scale': 'scale 0.7s ease-in-out',
        'shimmer': 'shimmer 2s linear infinite',
        'tilt': 'tilt 10s infinite linear',
        'fadeInUp': 'fadeInUp 0.8s ease-out forwards',
        'fadeInDown': 'fadeInDown 0.8s ease-out forwards',
        'rotateIn': 'rotateIn 0.8s ease-out forwards',
        'blurIn': 'blurIn 0.8s ease-out forwards',
        'slideLeft': 'slideLeft 40s linear infinite',
        'slideLeft-pause': 'slideLeft 40s linear infinite paused',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInFromLeft: {
          '0%': { opacity: '0', transform: 'translateX(-30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInFromRight: {
          '0%': { opacity: '0', transform: 'translateX(30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        zoomIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        float: {
          '0%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
          '100%': { transform: 'translateY(0px)' },
        },
        glow: {
          '0%': { textShadow: '0 0 5px rgba(67, 97, 238, 0.3), 0 0 15px rgba(67, 97, 238, 0.2)' },
          '50%': { textShadow: '0 0 20px rgba(67, 97, 238, 0.5), 0 0 30px rgba(67, 97, 238, 0.3)' },
          '100%': { textShadow: '0 0 5px rgba(67, 97, 238, 0.3), 0 0 15px rgba(67, 97, 238, 0.2)' },
        },
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-100%)' },
        },
        marquee2: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0%)' },
        },
        'marquee-pause': {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-100%)' },
        },
        'marquee2-pause': {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0%)' },
        },
        scale: {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.05)' },
          '100%': { transform: 'scale(1)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        tilt: {
          '0%, 50%, 100%': { transform: 'rotate(0deg)' },
          '25%': { transform: 'rotate(0.5deg)' },
          '75%': { transform: 'rotate(-0.5deg)' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInDown: {
          '0%': { opacity: '0', transform: 'translateY(-20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        rotateIn: {
          '0%': { opacity: '0', transform: 'rotate(-5deg) scale(0.95)' },
          '100%': { opacity: '1', transform: 'rotate(0) scale(1)' },
        },
        blurIn: {
          '0%': { opacity: '0', filter: 'blur(10px)' },
          '100%': { opacity: '1', filter: 'blur(0)' },
        },
        slideLeft: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-100%)' },
        },
      },
      boxShadow: {
        'glow-primary': '0 0 15px rgba(67, 97, 238, 0.5)',
        'glow-gray': '0 0 15px rgba(166, 155, 123, 0.5)',
        'glow-light': '0 0 15px rgba(245, 231, 195, 0.5)',
        'card': '0 2px 10px rgba(0, 0, 0, 0.05)',
        'card-hover': '0 5px 15px rgba(0, 0, 0, 0.08)',
        'button': '0 1px 3px rgba(0, 0, 0, 0.1)',
        'button-hover': '0 3px 6px rgba(0, 0, 0, 0.15)',
        'soft': '0 2px 8px rgba(0, 0, 0, 0.03)',
        'elevated': '0 4px 12px rgba(0, 0, 0, 0.06)',
      },
      transitionProperty: {
        'height': 'height',
        'spacing': 'margin, padding',
      },
      transitionTimingFunction: {
        'bounce': 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
      },
    },
  },
  plugins: [],
}
